// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/sync-stablecoin-addresses.js
// Last updated: 2026-01-25T21:32:12.746Z
// Source: @juicedollar/jusd and @juiceswapxyz/sdk-core packages

/**
 * Stablecoin addresses by chain ID.
 * These tokens will display a fixed price of $1.00.
 */
export const STABLECOIN_ADDRESSES: Record<string, ReadonlyArray<string>> = {
  '4114': [
    '0xe045e6c36cf77faa2cfb54466d71a3aef7bbe839',
    '0x9f3096bac87e7f03dc09b0b416eb0df837304dc4',
    '0x8d82c4e3c936c7b5724a382a9c5a4e6eb7ab6d5d',
  ],
  '5115': [
    '0x6a850a548fdd050e8961223ec8ffcdfacea57e39',
    '0x8398da4c32eae51b9840da230095bb29f4179590',
  ],
};

/**
 * Wrapped native token addresses by chain ID (e.g., WcBTC on Citrea).
 * These tokens will use the native currency exchange rate.
 */
export const WRAPPED_NATIVE_ADDRESSES: Record<string, string> = {
  '4114': '0x3100000000000000000000000000000000000006',
  '5115': '0x8d0c9d1c17ae5e40fff9be350f57840e9e66cd93',
};

/**
 * ERC-4626 Vault token addresses by chain ID.
 * These tokens use pricePerShare from on-chain data (totalAssets/totalSupply).
 * The underlying asset is assumed to be a stablecoin worth $1.00.
 */
export const VAULT_TOKEN_ADDRESSES: Record<string, ReadonlyArray<string>> = {
  '5115': [
    '0x802a29bd29f02c8c477af5362f9ba88fae39cc7b',
  ],
};

/**
 * Equity token addresses by chain ID (e.g., JUICE).
 * These tokens have a built-in price() function that returns the current price.
 */
export const EQUITY_TOKEN_ADDRESSES: Record<string, ReadonlyArray<string>> = {
  '5115': [
    '0x7fa131991c8a7d8c21b11391c977fc7c4c8e0d5e',
  ],
};
