// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/sync-stablecoin-addresses.js
// Last updated: 2026-01-25T17:10:00.000Z
// Source: @juicedollar/jusd and @juiceswapxyz/sdk-core packages

/**
 * Stablecoin addresses by chain ID.
 * These tokens will display a fixed price of $1.00.
 */
export const STABLECOIN_ADDRESSES: Record<string, ReadonlyArray<string>> = {
  '4114': [
    '0xe045e6c36cf77faa2cfb54466d71a3aef7bbe839',
    '0x9f3096bac87e7f03dc09b0b416eb0df837304dc4',
    '0x8d82c4e3c936c7b5724a382a9c5a4e6eb7ab6d5d',
  ],
  '5115': [
    '0x6a850a548fdd050e8961223ec8ffcdfacea57e39',
    '0x8398da4c32eae51b9840da230095bb29f4179590',
  ],
};

/**
 * Wrapped native token addresses by chain ID (e.g., WcBTC on Citrea).
 * These tokens will use the native currency exchange rate.
 */
export const WRAPPED_NATIVE_ADDRESSES: Record<string, string> = {
  '4114': '0x3100000000000000000000000000000000000006',
  '5115': '0x8d0c9d1c17ae5e40fff9be350f57840e9e66cd93',
};
